### ISSUE TITLE
MappedByteBuffer is not compatible with MATLAB java version. 

### ISSUE THREAD

**Issue by ferhatyaman** [Riscure/java-trsfile#47]
This line throws the exception below.
https://github.com/Riscure/java-trsfile/blob/e47cb73f5559a7512a82be11a5d9471e30a8fdab/src/main/java/com/riscure/trs/TraceSet.java#L144

`Java exception occurred: java.lang.NoSuchMethodError: java.nio.MappedByteBuffer.position(I)Ljava/nio/MappedByteBuffer;`

I think the MATLAB(2021a) java version is not compatible with the version used in this repo. I have overcome the problem of changing that line casting superclass of MappedByteBuffer.

`((Buffer)buffer).position((int) (absolutePosition - this.bufferStart));`

FYI

**Comment by Siebje** [comment]
Thanks for the report. I've noticed the same thing, and it seems to be a bug in the Java8 cross compiler for OpenJDK11. Great to know that inserting a manual cast solves the problem.
